"""Provider-independent product core for Empy Studio."""

from .contracts import (
    AIDriver,
    DriverCapabilities,
    DriverExecutionRequest,
    DriverExecutionResult,
    DriverStatus,
    ProjectDescriptor,
    ProjectService,
    WorkspaceStore,
)

__all__ = [
    "TASK_TEMPLATES",
    "AIDriver",
    "AgentTokenAllocation",
    "BudgetDecision",
    "BudgetEvent",
    "BudgetPreset",
    "BudgetRunState",
    "BudgetStatus",
    "ContextExclusion",
    "ContextFile",
    "ContextPack",
    "ContextPolicy",
    "ContextSelection",
    "DefaultProjectService",
    "DriverCapabilities",
    "DriverExecutionRequest",
    "DriverExecutionResult",
    "DriverStatus",
    "ExecutionPlan",
    "PlanStep",
    "ProductTask",
    "ProjectBrain",
    "ProjectDescriptor",
    "ProjectDetection",
    "ProjectService",
    "StepBudgetUsage",
    "TaskKind",
    "TaskTemplate",
    "TokenBudget",
    "TokenBudgetPolicy",
    "UsageKind",
    "WorkspaceStore",
    "apply_budget_usage",
    "approve_execution_plan",
    "build_context_selection",
    "build_product_task",
    "build_token_budget",
    "cancel_execution_plan",
    "estimate_tokens",
    "generate_execution_plan",
    "lock_token_budget",
    "mark_ready_for_planning",
    "policy_for_preset",
    "split_multiline",
    "start_budget_run",
    "template_by_key",
]

from .context_selector import (
    ContextExclusion,
    ContextFile,
    ContextPack,
    ContextPolicy,
    ContextSelection,
    ProjectBrain,
    build_context_selection,
)
from .planner import (
    ExecutionPlan,
    PlanStep,
    approve_execution_plan,
    cancel_execution_plan,
    generate_execution_plan,
)
from .project_service import (
    DefaultProjectService,
    ProjectDetection,
)
from .task_intake import (
    TASK_TEMPLATES,
    ProductTask,
    TaskKind,
    TaskTemplate,
    build_product_task,
    mark_ready_for_planning,
    split_multiline,
    template_by_key,
)
from .token_budget import (
    AgentTokenAllocation,
    BudgetDecision,
    BudgetEvent,
    BudgetPreset,
    BudgetRunState,
    BudgetStatus,
    StepBudgetUsage,
    TokenBudget,
    TokenBudgetPolicy,
    UsageKind,
    apply_budget_usage,
    build_token_budget,
    estimate_tokens,
    lock_token_budget,
    policy_for_preset,
    start_budget_run,
)
